### 목표 설정
- 선형 회귀의 사용법 알아보기
- 학습된 선형 회귀 모델의 가중치와 편향 확인해보기
- 어떤 모델을 사용할 것인가 ? : 선형 회귀
- 어떤 데이터를 이용할 것인가 ? : numpy로 만든 단순한 수치데이터

In [1]:
import numpy as np

In [2]:
X = np.arange(1,10,2)
X

array([1, 3, 5, 7, 9])

In [3]:
y=np.arange(10,100,20)
y

array([10, 30, 50, 70, 90])

### 필요한 모델 불러오기
- 선형 회귀 모델

In [4]:
from sklearn.linear_model import LinearRegression

In [5]:
linear = LinearRegression()

In [7]:
# X 데이터를 2차원으로 바꿔주자
X_ = X.reshape(5,1)
X_

array([[1],
       [3],
       [5],
       [7],
       [9]])

In [9]:
# 선형 회귀를 사용할 때 특성 데이터는 2차원 형태를 가지고 있어야 한다.(주의사항)
linear.fit(X_,y)

LinearRegression()

In [14]:
# 선형 회귀 모델 예측
pre = linear.predict([[6]])
print(pre)

[60.]


In [15]:
# 학습된 선형 회귀 모델의 가중치를 확인하는 명령어
linear.coef_

array([10.])

In [18]:
# 학습된 선형 회귀 모델의 편향을 확인하는 명령어
int(linear.intercept_)

0